### ISSUE TITLE
few bugs and tune ups 

### ISSUE THREAD

**Issue by dfeistel3** [baymlab/wastewater_analysis#4]
hi! Few small things:

I think in the call_variant.sh script it would be convenient if the user can add an additional argument for the reference sequence pathway, or indicate to the user that it needs to add that in.  As of now the pathway is hardcoded to a directory in your environment with the reference.  

Also I noticed that some of the version for bcftools, vcftool, and ivar (for the trimming step) seem to be version depended. Could you list out what versions of the tools you use?

last, for the first preprocessing step, you have `---o reference_set` instead of `--o`

**Comment by EvaFriederike** [comment]
Hi :)
First of all, thank you for sharing your code!

Some time ago, I reused your pipeline version with git hash 61dd29d* from Sep 16, 2021 and into an issue with the call_variant.sh script:
With more current bcftools versions (I used 1.3.1), the `-0` parameter that relabels the missing allternate alleles (_./._) to reference alleles (_0/0_) is not provided anymore. 
So in order to not run into issues with the alternate allele frequency computation and downstream sequence filtering, I had to manually replace these labellings in the merged vcf files. Could you provide a list with all technical requirements and version information? That would really help replicating your pipeline.
